### ISSUE TITLE
Question about Step 6: add split-tunnel connection to your config

### ISSUE THREAD

**Issue by ghost** [mgrimace/PiHole-with-PiVPN-and-Unbound-on-VPS-#4]
Hello,

i just followed your guide to setup my VPS with pihole and pivpn, thank your for that!
however i got confused at the aformentioned part of the guide and am not sure if i did it correctly.

my server has an IPV4 and an IPV6 adress, lets say [IPV4]/24 and [IPV6]::1. Do i still need to use /32 in the adress and DNS part of the AllowedIPs config? And where does the IPV6 address go?

[config.txt](https://github.com/mgrimace/PiHole-with-PiVPN-and-Unbound-on-VPS-/files/7981438/config.txt)

**Comment by mgrimace** [comment]
Hello @stunlocked94, I'm glad you found this helpful! Your server will have its own addresses and should be listed as an IPV4 and IPV6. For step 6 you're modifying your Wireguard client configs to connect back directly to your virtual server, and only for DNS queries. So what you're putting into the Wireguard config file is only the IPV4 address with the ending /32 (not /24) because /32 tells it to use *exactly* that address, where /24 allows a range. You shouldn't need to bother with IPV6 in the config files at all. You'll also add the exact address of your PiHole web server IPV4/32 so you can connect to there.

This is the profile that gets loaded into your device using Wireguard, so you'l have a config for each device (e.g., I have one for my laptop, and one for my phone). If you don't want to edit this in SSH, you can also just load up the configs as they are and edit them using the Wireguard app on your computer.

I'm still learning a lot myself, so I'm not 100% sure that's totally accurate but hopefully helps!
~M

**Comment by ghost** [comment]
Hello

Thank you for the fast and thorough response!
